// ─────────────────────────────────────────────────────
//  MOTS MYSTÈRES — MAJUSCULES, sans accents, 5 à 18 lettres
// ─────────────────────────────────────────────────────
const SECRETS_LIST = [
  "BRAVO","SUPER","GENIE","FORCE","HEROS","MALIN","AGILE",
  "TALENT","LUCIDE","ARDEUR","SOLEIL",
  "PARFAIT","COURAGE","FINESSE","ADRESSE","PRODIGE","VICTOIRE",
  "CHAMPION","TRIOMPHE","GLORIEUX","BRILLANT",
  "MERVEILLE","GRANDIOSE","EXCELLENT",
  "FORMIDABLE","PRODIGIEUX","INVINCIBLE",
  "MAGNIFIQUE","REMARQUABLE",
  "INIMAGINABLE","FELICITATIONS",
  "CONGRATULATION","INCONTOURNABLE","IRREMPLACEABLE",
  "BOULEVERSEMENT","RETENTISSEMENT","RECONNAISSABLE",
  "IMPECCABLEMENT","EXTRAORDINAIRE","INSOUPCONNABLE",
];

// ─────────────────────────────────────────────────────
//  THÈMES — MAJUSCULES, sans accents, 3 à 12 lettres
// ─────────────────────────────────────────────────────
const THEMES = {

  animaux: [
    "CHAT","CHIEN","LION","TIGRE","OURS","RENARD","LOUP","AIGLE",
    "REQUIN","DAUPHIN","VACHE","CHEVAL","LAPIN","SERPENT","SINGE",
    "PERROQUET","MOUTON","HIBOU","PANDA","ZEBRE","BALEINE","TORTUE",
    "AUTRUCHE","PUMA","LYNX","BISON","PHOQUE","FOURMI","COLOMBE",
    "LOUTRE","JAGUAR","GUEPARD","GIRAFE","GORILLE","CHAMEAU","LAMA",
    "COYOTE","TAPIR","OKAPI","SURICATE","TATOU","CAIMAN","VARAN",
    "GECKO","IGUANE","COBRA","MAMBA","CONDOR","TOUCAN","IBIS",
    "FLAMANT","MANCHOT","ALBATROS","NARVAL","ORQUE","LAMANTIN",
    "CAPYBARA","WOMBAT","KOALA","QUOKKA",
  ],

  fruits: [
    "POMME","BANANE","KIWI","RAISIN","MANGUE","FRAISE","CERISE",
    "ANANAS","PECHE","POIRE","CITRON","ORANGE","PRUNE","MELON",
    "FRAMBOISE","ABRICOT","FIGUE","PAPAYE","COCO","GRENADE",
    "LITCHI","MYRTILLE","MURE","BRUGNON","DATTE","CASSIS",
    "GROSEILLE","MIRABELLE","COING","NECTARINE","MARACUJA",
    "RAMBOUTAN","PITAYA","LONGAN","YUZU","COMBAVA","CEDRAT",
    "BIBASSE","PAMPLEMOUSSE","MANDARINE","CLEMENTINE","AVOCAT",
    "TOMATE","AUBERGINE","POIVRON","CORNICHON","CONCOMBRE",
    "RHUBARBE","AIRELLE","SUREAU",
  ],

  sports: [
    "FOOT","RUGBY","TENNIS","NATATION","CYCLISME","BOXE","GOLF",
    "BASKET","VOLLEY","HANDBALL","JUDO","KARATE","ESCRIME","AVIRON",
    "SURF","SKI","PATINAGE","LUTTE","PLONGEON","EQUITATION",
    "ESCALADE","BIATHLON","CURLING","LUGE","TRIATHLON","FLEURET",
    "SABRE","EPEE","CRAWL","MARATHON","SPRINT","RELAIS","PERCHE",
    "DISQUE","MARTEAU","JAVELOT","CROSS","BOULES","POLO","SAMBO",
    "AIKIDO","KENDO","TAEKWONDO","TRAMPOLINE","DECATHLON","BOBSLEIGH",
    "SKELETON","PARACHUTE","KAYAK","RAFTING","WAKEBOARD","KITESURF",
  ],

  pays: [
    "FRANCE","ESPAGNE","ITALIE","JAPON","CHINE","BRESIL","CANADA",
    "MEXIQUE","INDE","RUSSIE","TURQUIE","EGYPTE","MAROC","ALGERIE",
    "GHANA","IRAN","PEROU","CUBA","CHILI","SUEDE","NORVEGE",
    "FINLANDE","POLOGNE","AUTRICHE","BELGIQUE","SUISSE","PORTUGAL",
    "GRECE","SERBIE","CROATIE","BULGARIE","ROUMANIE","UKRAINE",
    "GEORGIE","ARMENIE","MYANMAR","VIETNAM","CAMBODGE","LAOS",
    "NEPAL","MONGOLIE","ANGOLA","ZAMBIE","ZIMBABWE","TANZANIE",
    "KENYA","OUGANDA","RWANDA","NIGERIA","CAMEROUN","SENEGAL",
    "TUNISIE","LIBYE","TCHAD","MALI","NIGER","GABON","CONGO",
  ],

  couleurs: [
    "ROUGE","BLEU","VERT","JAUNE","ORANGE","VIOLET","ROSE","GRIS",
    "BLANC","NOIR","BEIGE","CYAN","INDIGO","MARRON","CORAIL","AZUR",
    "OCRE","LILAS","TURQUOISE","ECARLATE","CRAMOISI","EMERAUDE",
    "SAPHIR","RUBIS","AMBRE","IVOIRE","ACIER","BRIQUE","SABLE",
    "OLIVE","VERMILLON","CARMIN","MAGENTA","FUCHSIA","LAVANDE",
    "CELADON","KAKI","CHAMOIS","GRENAT","BORDEAUX","BOURGOGNE",
    "AUBURN","ACAJOU","NOISETTE","CARAMEL","CHOCOLAT","MOUTARDE",
    "SAFRAN","CANARI","MENTHE","PISTACHE","JADE","MALACHITE",
    "COBALT","MARINE","ARDOISE","ANTHRACITE","EBENE","NACRE",
  ],

  metiers: [
    "MEDECIN","PILOTE","POMPIER","CUISINIER","AVOCAT","JUGE",
    "ACTEUR","DANSEUR","CHANTEUR","PEINTRE","SCULPTEUR","INGENIEUR",
    "ARCHITECTE","INFIRMIER","PHARMACIEN","LIBRAIRE","MENUISIER",
    "PLOMBIER","COIFFEUR","JARDINIER","BOUCHER","BOULANGER",
    "ELECTRICIEN","CHARPENTIER","VITRIER","SERRURIER","FORGERON",
    "POTIER","CARRELEUR","VETERINAIRE","BIOLOGISTE","CHIMISTE",
    "PHYSICIEN","GEOLOGUE","HISTORIEN","PSYCHOLOGUE","CHIRURGIEN",
    "RADIOLOGUE","CARDIOLOGUE","PEDIATRE","NEPHROLOGUE","NEUROLOGUE",
    "BANQUIER","COMPTABLE","ECONOMISTE","URBANISTE","PAYSAGISTE",
    "PHOTOGRAPHE","JOURNALISTE","REDACTEUR","TRADUCTEUR","NOTAIRE",
    "MAGISTRAT","GENDARME","DOUANIER","INSPECTEUR","DIPLOMATE",
  ],

  nature: [
    "FORET","OCEAN","RIVIERE","MONTAGNE","DESERT","PRAIRIE","VOLCAN",
    "GLACIER","FALAISE","LAGUNE","CANYON","DELTA","TOUNDRA","SAVANE",
    "MARAIS","COLLINE","VALLEE","PLATEAU","DUNE","GROTTE","TORRENT",
    "ESTUAIRE","ARCHIPEL","ATOLL","FJORD","STEPPE","PAMPA","MAQUIS",
    "LANDE","SOURCE","TOURBIERE","MANGROVE","GARRIGUE","BROUSSE",
    "TAIGA","BANQUISE","ICEBERG","GEYSER","FUMAROLE","STALAGMITE",
    "STALACTITE","CALCAIRE","GRANITE","BASALTE","SCHISTE","SILEX",
    "FOUGERE","MOUSSE","LICHEN","CHAMPIGNON","TRUFFE","ORCHIDEE",
    "BAMBOU","SEQUOIA","BAOBAB","CACTUS","ROSEAU","LOTUS",
  ],

  corps: [
    "BRAS","JAMBE","TETE","COEUR","FOIE","REIN","POUMON","GENOU",
    "COUDE","EPAULE","CHEVILLE","POIGNET","NUQUE","MENTON","TEMPE",
    "NARINE","PAUME","TALON","STERNUM","CLAVICULE","TIBIA","HANCHE",
    "ROTULE","SACRUM","COCCYX","FEMUR","RADIUS","CUBITUS","PHALANGE",
    "MALLEOLE","TRACHEE","OESOPHAGE","ESTOMAC","INTESTIN","PANCREAS",
    "RATE","THYROIDE","HYPOPHYSE","AMYGDALE","APPENDICE","DIAPHRAGME",
    "TYMPAN","CRISTALLIN","COCHLEE","MANDIBULE","MAXILLAIRE",
    "VERTEBRE","CARTILAGE","LIGAMENT","TENDON","AORTE","ARTERE",
    "VEINE","CAPILLAIRE","NEURONE","SYNAPSE","CHROMOSOME",
  ],

  musique: [
    "GUITARE","PIANO","VIOLON","TROMPETTE","FLUTE","HARPE",
    "ACCORDEON","TUBA","HAUTBOIS","CLARINETTE","BASSON","TROMBONE",
    "CORNET","BUGLE","LUTH","MANDOLINE","BANJO","UKULELE",
    "BALALAIKA","SITAR","TABLA","DJEMBE","CONGAS","MARACAS",
    "XYLOPHONE","VIBRAPHONE","MARIMBA","CARILLON","CLAVECIN",
    "ORGUE","HARMONIUM","CONTREBASSE","VIOLONCELLE","ALTO","PICCOLO",
    "FLAGEOLET","OCARINA","CORNEMUSE","DULCIMER","CITHARE","VIELLE",
    "REBEC","THEORBE","KORA","BALAFON","MBIRA","STEELDRUM",
    "GAMELAN","TAIKO","BOUZOUKI","DIDGERIDOO",
  ],

  cuisine: [
    "SOUPE","SALADE","GRATIN","RAGOUT","RISOTTO","PAELLA","TAJINE",
    "COUSCOUS","LASAGNE","RAVIOLI","GNOCCHI","POLENTA","FONDUE",
    "RACLETTE","QUICHE","TARTE","CLAFOUTIS","COMPOTE","COULIS",
    "SORBET","MOUSSE","MERINGUE","MACARON","MADELEINE","BEIGNET",
    "CREPE","GALETTE","BRIOCHE","CROISSANT","BAGUETTE","FOCACCIA",
    "CHAPATI","NAAN","TORTILLA","EMPANADA","SUSHI","TEMPURA",
    "RAMEN","BIBIMBAP","KIMCHI","MISO","SHAKSHUKA","HUMMUS",
    "TABOULE","BAKLAVA","TIRAMISU","CANNOLI","BRUSCHETTA",
    "CARPACCIO","GAZPACHO","BOUILLABAISSE","CASSOULET","RATATOUILLE",
    "BRANDADE","TAPENADE","BLANQUETTE","CARBONNADE",
  ],

  transports: [
    "VOITURE","AVION","TRAIN","BATEAU","VELO","MOTO","BUS","METRO",
    "TRAMWAY","TAXI","FERRY","CARGO","TANKER","HELICOPTER","PLANEUR",
    "DIRIGEABLE","NAVETTE","FUSEE","TRACTEUR","CAMION","DESTROYER",
    "CATAMARAN","TRIMARAN","KAYAK","PIROGUE","JONQUE","GALION",
    "GALERE","CARAVELLE","GOELETTE","CLIPPER","REMORQUEUR",
    "CHALUTIER","PAQUEBOT","HOVERCRAFT","HYDROFOIL","SKIDOO",
    "QUAD","TROTTINETTE","CHARIOT","BROUETTE","LANDAU","SULKY",
    "TRAINEAU","MONORAIL","FUNICULAIRE","TELEPHERIQUE","SCOOTER",
    "SIDECAR","TRICYCLE","TANDEM",
  ],

  informatique: [
    "ORDINATEUR","CLAVIER","SOURIS","ECRAN","SERVEUR","RESEAU",
    "INTERNET","LOGICIEL","PROGRAMME","ALGORITHME","VARIABLE",
    "FONCTION","BOUCLE","TABLEAU","OBJET","CLASSE","METHODE",
    "MODULE","LIBRAIRIE","FRAMEWORK","INTERFACE","PROTOCOLE",
    "NAVIGATEUR","REQUETE","JOINTURE","TRANSACTION","CRYPTAGE",
    "CERTIFICAT","ANTIVIRUS","ROUTEUR","COMMUTATEUR","MODEM",
    "PROCESSEUR","MEMOIRE","STOCKAGE","DISQUE","PARTITION",
    "SYSTEME","NOYAU","DAEMON","PROCESSUS","THREAD","SOCKET",
    "PAQUET","SIGNAL","BIT","OCTET","PIXEL","VECTEUR","MATRICE",
    "RECURSION","ITERATEUR","GENERATEUR","DECORATEUR","SINGLETON",
  ],

  geographie: [
    "EQUATEUR","TROPIQUE","MERIDIEN","LATITUDE","LONGITUDE",
    "ALTITUDE","RELIEF","EROSION","SEDIMENT","ALLUVION",
    "TECTONIQUE","SUBDUCTION","OROGENIE","GLACIATION","PERMAFROST",
    "MORAINE","CIRQUE","CREVASSE","KARST","DOLINE","TALWEG",
    "VERSANT","BASSIN","CONFLUENCE","MEANDRE","ECLUSE","BARRAGE",
    "NAPPE","RESURGENCE","AQUIFERE","ISOBARE","ISOTHERME",
    "ANTICYCLONE","DEPRESSION","ZENITH","NADIR","SOLSTICE",
    "EQUINOXE","APOGEE","PERIGEE","ECLIPSE","LITHOSPHERE",
    "MAGNETOSPHERE","TROPOSPHERE","STRATOSPHERE","MESOSPHERE",
    "IONOSPHERE","PEDOSPHERE","BIOSPHERE","CHROMOSPHERE",
  ],

};
